build: pip install -r requirements.txt

tests:
  unit: PYTHONPATH=. pytest tests/unit
  integration: PYTHONPATH=. pytest tests/integration || true

deploy:
  staging: echo "Deploying service-b to staging..."
  production: echo "Deploying service-b to production..."
