name: Smart CI/CD (MVP1)

on:
  push:
    branches:
      - main
      - '**'
  pull_request:

jobs:
  detect-components:
    runs-on: ubuntu-latest
    outputs:
      components: ${{ steps.detect.outputs.components }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install tools
        run: sudo apt-get update && sudo apt-get install -y yq jq

      - name: Get changed files
        id: changes
        run: |
          echo "Detecting changed files..."
          echo "" > changes.txt

          # Try to pull changed files from event payload (if available)
          FILES=$(jq -r '[.commits[]? | .added[], .modified[], .removed[]] | unique | .[]?' <<< '${{ toJson(github.event) }}')

          if [ -n "$FILES" ]; then
            echo "$FILES" > changes.txt
            echo "Changed files detected from event payload:"
            cat changes.txt
          else
            echo "⚠️ No files from event payload, falling back to git diff"
            if git rev-parse HEAD~1 >/dev/null 2>&1; then
              git diff --name-only HEAD~1 HEAD > changes.txt
            else
              git ls-files > changes.txt
            fi
            echo "Changed files detected:"
            cat changes.txt
          fi


      - name: Detect impacted components
        id: detect
        run: |
          echo "### Detecting impacted components ###"
          CHANGED=$(cat changes.txt)
          COMPONENTS_FILE=components.tmp
          > $COMPONENTS_FILE
          DEPS=$(cat dependencies.json)

          echo "" > impact.log

          for FILE in $CHANGED; do
            IMPACTED=()

            # Walk up directories until we find ci-config.yml
            DIR=$(dirname "$FILE")
            while [ "$DIR" != "/" ] && [ "$DIR" != "." ]; do
              if [ -f "$DIR/ci-config.yml" ]; then
                IMPACTED+=("$DIR")
              fi
              DIR=$(dirname "$DIR")
            done

            # Dependency expansion (jq, since DEPS is JSON)
            NEW_IMPACTED=()
            for COMP in "${IMPACTED[@]}"; do
              echo "Checking impacted component: $COMP" >> impact.log
              NEW_IMPACTED+=("$COMP")
              for OTHER in $(echo "$DEPS" | jq -r 'keys[]'); do
                echo "  Does $OTHER depend on $COMP ?" >> impact.log
                if echo "$DEPS" | jq -e ".\"$OTHER\" | index(\"$COMP\")" > /dev/null; then
                  echo "    ✅ Yes, adding $OTHER" >> impact.log
                  NEW_IMPACTED+=("$OTHER")
                else
                  echo "    ❌ No" >> impact.log
                fi
              done
            done

            printf "%s\n" "${NEW_IMPACTED[@]}" | grep -v '^$' | sort -u >> $COMPONENTS_FILE
            echo "$FILE → [$(printf "%s " "${NEW_IMPACTED[@]}" | xargs)]" >> impact.log
          done

          VALID_KEYS=$(echo "$DEPS" | jq -r 'keys[]')
          FILTERED=$(sort -u $COMPONENTS_FILE | grep -v '^$' | grep -Fxf <(echo "$VALID_KEYS"))
          UNIQUE=$(echo "$FILTERED" | jq -R . | jq -s -c .)

          if [ -z "$UNIQUE" ] || [ "$UNIQUE" = "[]" ]; then
            UNIQUE='["noop"]'
          fi

          echo "### Final impacted components: $UNIQUE ###"
          echo "components=$UNIQUE" >> $GITHUB_OUTPUT
          echo "### Changed file → Impacted components table ###"
          cat impact.log || true

      - name: Upload impact report
        uses: actions/upload-artifact@v4
        with:
          name: impact-report
          path: impact.log

  build:
    needs: detect-components
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        component: ${{ fromJson(needs.detect-components.outputs.components) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install tools
        if: matrix.component != 'noop'
        run: sudo apt-get update && sudo apt-get install -y yq jq

      - name: Skip if noop
        if: matrix.component == 'noop'
        run: echo "✅ No impacted components, skipping build."

      - name: Build & Run Tests
        if: matrix.component != 'noop'
        run: |
          echo "============================"
          echo "🏗️ Building component: ${{ matrix.component }}"
          echo "============================"
          cd "${{ matrix.component }}"
          CONFIG="ci-config.yml"
          if [ -f "$CONFIG" ]; then
            BUILD_CMD=$(yq -r '.build' $CONFIG)
            echo "🔨 Build: $BUILD_CMD"
            eval "$BUILD_CMD"

            TESTS=$(yq -r '.tests | keys[]' $CONFIG || true)
            for TEST in $TESTS; do
              CMD=$(yq -r ".tests[\"$TEST\"]" $CONFIG)
              echo "🧪 Running $TEST tests: $CMD"
              eval "$CMD"
            done
          else
            echo "⚠️ No ci-config.yml found in ${{ matrix.component }}"
          fi
