name: Smart CI/CD (Universal MVP1 with Debug Logs)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  detect-components:
    runs-on: ubuntu-latest
    outputs:
      components: ${{ steps.detect.outputs.components }}
    steps:
      - uses: actions/checkout@v3

      - name: Get changed files
        run: |
          git fetch origin main
          git diff --name-only origin/main...HEAD > changes.txt
          echo "### Changed files in this commit/PR ###"
          cat changes.txt || echo "No changed files detected"

      - name: Detect impacted components
        id: detect
        run: |
          echo "### Detecting impacted components ###"
          CHANGED=$(cat changes.txt)
          COMPONENTS=""
          DEPS=$(cat dependencies.json)

          for FILE in $CHANGED; do
            ROOT=$(echo $FILE | cut -d'/' -f1-2)
            echo "File changed: $FILE → mapping to root: $ROOT"
            COMPONENTS="$COMPONENTS $ROOT"

            for COMP in $(echo $DEPS | jq -r 'keys[]'); do
              if echo $DEPS | jq -e ".\"$COMP\" | index(\"$ROOT\")" > /dev/null; then
                echo "Dependency match: $ROOT impacts $COMP"
                COMPONENTS="$COMPONENTS $COMP"
              fi
            done
          done

          # Remove duplicates, ensure JSON array, fallback to []
          UNIQUE=$(echo $COMPONENTS | tr ' ' '\n' | grep -v '^$' | sort -u | jq -R . | jq -s .)
          if [ -z "$UNIQUE" ] || [ "$UNIQUE" = "null" ]; then
            UNIQUE="[]"
          fi

          echo "### Final impacted components: $UNIQUE ###"
          echo "components=$UNIQUE" >> $GITHUB_OUTPUT

  build:
    needs: detect-components
    if: needs.detect-components.outputs.components != '[]'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component: ${{ fromJson(needs.detect-components.outputs.components) }}
    steps:
      - uses: actions/checkout@v3

      - name: Read build config
        id: config
        run: |
          CONFIG_FILE="${{ matrix.component }}/build-config.json"
          echo ">>> Checking build config for component: ${{ matrix.component }}"
          if [ -f "$CONFIG_FILE" ]; then
            BUILD_CMD=$(jq -r '.build' $CONFIG_FILE)
            TEST_CMD=$(jq -r '.test' $CONFIG_FILE)
            echo "Found build-config.json → build: $BUILD_CMD | test: $TEST_CMD"
          else
            BUILD_CMD="echo 'No build step'"
            TEST_CMD="echo 'No test step'"
            echo "⚠️ No build-config.json found for ${{ matrix.component }}. Skipping actual build/test."
          fi
          echo "build_cmd=$BUILD_CMD" >> $GITHUB_OUTPUT
          echo "test_cmd=$TEST_CMD" >> $GITHUB_OUTPUT

      - name: Build & Test Component
        run: |
          echo "======================================"
          echo ">>> STARTING PARTIAL BUILD for component: ${{ matrix.component }}"
          echo "======================================"
          cd ${{ matrix.component }}
          bash -c "${{ steps.config.outputs.build_cmd }}"
          bash -c "${{ steps.config.outputs.test_cmd }}"
          echo "✅ Completed build & test for ${{ matrix.component }}"
